"""empty message

Revision ID: 01efb8b75f5f
Revises: 297dbea3c63d
Create Date: 2019-03-20 11:28:27.019666

"""

# revision identifiers, used by Alembic.
revision = '01efb8b75f5f'
down_revision = '297dbea3c63d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###
