"""empty message

Revision ID: 73433710d40c
Revises: 203f3901e673
Create Date: 2019-03-20 12:33:50.021856

"""

# revision identifiers, used by Alembic.
revision = '73433710d40c'
down_revision = '203f3901e673'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
