"""empty message

Revision ID: fb484a5352ce
Revises: bec51d9ed3b6
Create Date: 2019-03-24 22:51:12.277105

"""

# revision identifiers, used by Alembic.
revision = 'fb484a5352ce'
down_revision = 'bec51d9ed3b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('website_name', sa.String(length=500), nullable=True),
    sa.Column('image', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
